import type { ImagePlaceholder } from './definitions';

export const PlaceHolderImages: ImagePlaceholder[] = [
  // ===== HERO IMAGE =====
  {
    id: 'hero-home',
    imageUrl: '/banner.jpg',
    description: 'Modern luxury interior design showcase',
    imageHint: 'hero-banner',
    width: 1920,
    height: 1080,
  },

  // ===== CATEGORY IMAGES =====
  {
    id: 'cat-residential',
    imageUrl: '/banner.jpg',
    description: 'Residential interior design',
    imageHint: 'category-residential',
    width: 800,
    height: 600,
  },
  {
    id: 'cat-corporate',
    imageUrl: '/banner.jpg',
    description: 'Commercial office space design',
    imageHint: 'category-commercial',
    width: 800,
    height: 600,
  },
  {
    id: 'cat-hospitality',
    imageUrl: '/banner.jpg',
    description: 'Hospitality interior design',
    imageHint: 'category-hospitality',
    width: 800,
    height: 600,
  },
  {
    id: 'cat-healthcare',
    imageUrl: '/banner.jpg',
    description: 'Healthcare facility design',
    imageHint: 'category-healthcare',
    width: 800,
    height: 600,
  },
  {
    id: 'cat-artwork',
    imageUrl: '/banner.jpg',
    description: 'Artistic interior elements',
    imageHint: 'category-artwork',
    width: 800,
    height: 600,
  },

  // ===== LIMPAIR OFFICE (Commercial/Office) - 5 images =====
  {
    id: 'cover-limpair-office',
    imageUrl: '/Limpairoffice/1.jpg',
    description: 'Limpair Office - Modern office exterior',
    imageHint: 'commercial-office-building',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-limpair-1',
    imageUrl: '/Limpairoffice/2.jpg',
    description: 'Limpair Office - Reception area',
    imageHint: 'office-interior-reception',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-limpair-2',
    imageUrl: '/Limpairoffice/3.jpg',
    description: 'Limpair Office - Workspace',
    imageHint: 'office-interior-workspace',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-limpair-3',
    imageUrl: '/Limpairoffice/4.jpg',
    description: 'Limpair Office - Meeting room',
    imageHint: 'office-interior-meeting',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-limpair-4',
    imageUrl: '/Limpairoffice/5.jpg',
    description: 'Limpair Office - Lounge area',
    imageHint: 'office-interior-lounge',
    width: 1200,
    height: 800,
  },

  // ===== DAMAN RESIDENCE (Residential/Bungalows) - 8 images =====
  {
    id: 'cover-daman-residence',
    imageUrl: '/damanresidence/1.jpg',
    description: 'Daman Residence - Exterior view',
    imageHint: 'residential-bungalow-exterior',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-1',
    imageUrl: '/damanresidence/2.jpg',
    description: 'Daman Residence - Living room',
    imageHint: 'residential-living-room',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-2',
    imageUrl: '/damanresidence/3.jpg',
    description: 'Daman Residence - Dining area',
    imageHint: 'residential-dining',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-3',
    imageUrl: '/damanresidence/4.jpg',
    description: 'Daman Residence - Master bedroom',
    imageHint: 'residential-bedroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-4',
    imageUrl: '/damanresidence/5.jpg',
    description: 'Daman Residence - Kitchen',
    imageHint: 'residential-kitchen',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-5',
    imageUrl: '/damanresidence/6.jpg',
    description: 'Daman Residence - Guest bedroom',
    imageHint: 'residential-guest-bedroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-6',
    imageUrl: '/damanresidence/7.jpg',
    description: 'Daman Residence - Bathroom',
    imageHint: 'residential-bathroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-7',
    imageUrl: '/damanresidence/8.jpg',
    description: 'Daman Residence - Outdoor space',
    imageHint: 'residential-outdoor',
    width: 1200,
    height: 800,
  },

  // ===== RESIDENCE (Residential/Flats) - 8 images (.JPG extension) =====
  {
    id: 'cover-residence',
    imageUrl: '/residence/1.JPG',
    description: 'Modern Residence - Apartment exterior',
    imageHint: 'residential-flat-exterior',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-1',
    imageUrl: '/residence/2.JPG',
    description: 'Modern Residence - Living space',
    imageHint: 'flat-interior-living',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-2',
    imageUrl: '/residence/3.JPG',
    description: 'Modern Residence - Kitchen',
    imageHint: 'flat-interior-kitchen',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-3',
    imageUrl: '/residence/4.JPG',
    description: 'Modern Residence - Bedroom',
    imageHint: 'flat-interior-bedroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-4',
    imageUrl: '/residence/5.JPG',
    description: 'Modern Residence - Balcony',
    imageHint: 'flat-interior-balcony',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-5',
    imageUrl: '/residence/6.JPG',
    description: 'Modern Residence - Additional room',
    imageHint: 'flat-interior-room',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-6',
    imageUrl: '/residence/7.JPG',
    description: 'Modern Residence - Detail view',
    imageHint: 'flat-interior-detail',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-7',
    imageUrl: '/residence/8.JPG',
    description: 'Modern Residence - Another angle',
    imageHint: 'flat-interior-angle',
    width: 1200,
    height: 800,
  },

  // ===== VALSAD RESIDENCE (Residential/Bungalows) - 11 images =====
  {
    id: 'cover-valsad-residence',
    imageUrl: '/valsadresidence/1.jpg',
    description: 'Valsad Residence - Front elevation',
    imageHint: 'residential-villa-exterior',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-1',
    imageUrl: '/valsadresidence/2.jpg',
    description: 'Valsad Residence - Entrance lobby',
    imageHint: 'residential-entrance',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-2',
    imageUrl: '/valsadresidence/3.jpg',
    description: 'Valsad Residence - Living area',
    imageHint: 'residential-living',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-3',
    imageUrl: '/valsadresidence/4.jpg',
    description: 'Valsad Residence - Dining room',
    imageHint: 'residential-dining',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-4',
    imageUrl: '/valsadresidence/5.jpg',
    description: 'Valsad Residence - Kitchen',
    imageHint: 'residential-kitchen',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-5',
    imageUrl: '/valsadresidence/6.jpg',
    description: 'Valsad Residence - Master bedroom',
    imageHint: 'residential-master-bedroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-6',
    imageUrl: '/valsadresidence/7.jpg',
    description: 'Valsad Residence - Guest bedroom',
    imageHint: 'residential-guest-bedroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-7',
    imageUrl: '/valsadresidence/8.jpg',
    description: 'Valsad Residence - Bathroom',
    imageHint: 'residential-bathroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-8',
    imageUrl: '/valsadresidence/9.jpg',
    description: 'Valsad Residence - Staircase',
    imageHint: 'residential-staircase',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-9',
    imageUrl: '/valsadresidence/10.jpg',
    description: 'Valsad Residence - Garden view',
    imageHint: 'residential-garden',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-10',
    imageUrl: '/valsadresidence/11.jpg',
    description: 'Valsad Residence - Terrace',
    imageHint: 'residential-terrace',
    width: 1200,
    height: 800,
  },

  // ===== GOURMET KITCHEN (Residential/Kitchen) - 3 images =====
  {
    id: 'cover-gourmet-kitchen',
    imageUrl: '/gourmetkitchen/1.jpg',
    description: 'Gourmet Kitchen - Main view',
    imageHint: 'kitchen-luxury-main',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-gourmet-kitchen-1',
    imageUrl: '/gourmetkitchen/2.jpg',
    description: 'Gourmet Kitchen - Details',
    imageHint: 'kitchen-luxury-details',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-gourmet-kitchen-2',
    imageUrl: '/gourmetkitchen/3.jpg',
    description: 'Gourmet Kitchen - Alternate view',
    imageHint: 'kitchen-luxury-alt',
    width: 1200,
    height: 800,
  },

  // ===== SPA BATHROOM (Residential/Bathroom) - 7 images =====
  {
    id: 'cover-spa-bathroom',
    imageUrl: '/spabathroom/1.jpg',
    description: 'Spa Bathroom - Main view',
    imageHint: 'bathroom-spa-main',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spa-bathroom-1',
    imageUrl: '/spabathroom/2.jpg',
    description: 'Spa Bathroom - Vanity area',
    imageHint: 'bathroom-spa-vanity',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spa-bathroom-2',
    imageUrl: '/spabathroom/3.jpg',
    description: 'Spa Bathroom - Shower area',
    imageHint: 'bathroom-spa-shower',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spa-bathroom-3',
    imageUrl: '/spabathroom/4.jpg',
    description: 'Spa Bathroom - Bathtub',
    imageHint: 'bathroom-spa-bathtub',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spa-bathroom-4',
    imageUrl: '/spabathroom/5.jpg',
    description: 'Spa Bathroom - Lighting details',
    imageHint: 'bathroom-spa-lighting',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spa-bathroom-5',
    imageUrl: '/spabathroom/6.jpg',
    description: 'Spa Bathroom - Decor elements',
    imageHint: 'bathroom-spa-decor',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spa-bathroom-6',
    imageUrl: '/spabathroom/7.jpg',
    description: 'Spa Bathroom - Wide view',
    imageHint: 'bathroom-spa-wide',
    width: 1200,
    height: 800,
  },

  // ===== SPICE ROUTE (Hospitality/Restaurant) - 14 images =====
  {
    id: 'cover-spice-route',
    imageUrl: '/spiceroute/1.jpg',
    description: 'Spice Route - Restaurant entrance',
    imageHint: 'restaurant-entrance',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-1',
    imageUrl: '/spiceroute/2.jpg',
    description: 'Spice Route - Dining area',
    imageHint: 'restaurant-dining',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-2',
    imageUrl: '/spiceroute/3.jpg',
    description: 'Spice Route - Bar area',
    imageHint: 'restaurant-bar',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-3',
    imageUrl: '/spiceroute/4.jpg',
    description: 'Spice Route - Private dining',
    imageHint: 'restaurant-private',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-4',
    imageUrl: '/spiceroute/5.jpg',
    description: 'Spice Route - Interior details 1',
    imageHint: 'restaurant-detail-1',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-5',
    imageUrl: '/spiceroute/6.jpg',
    description: 'Spice Route - Interior details 2',
    imageHint: 'restaurant-detail-2',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-6',
    imageUrl: '/spiceroute/7.jpg',
    description: 'Spice Route - Interior details 3',
    imageHint: 'restaurant-detail-3',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-7',
    imageUrl: '/spiceroute/8.jpg',
    description: 'Spice Route - Interior details 4',
    imageHint: 'restaurant-detail-4',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-8',
    imageUrl: '/spiceroute/9.jpg',
    description: 'Spice Route - Interior details 5',
    imageHint: 'restaurant-detail-5',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-9',
    imageUrl: '/spiceroute/10.jpg',
    description: 'Spice Route - Interior details 6',
    imageHint: 'restaurant-detail-6',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-10',
    imageUrl: '/spiceroute/11.jpg',
    description: 'Spice Route - Interior details 7',
    imageHint: 'restaurant-detail-7',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-11',
    imageUrl: '/spiceroute/12.jpg',
    description: 'Spice Route - Interior details 8',
    imageHint: 'restaurant-detail-8',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-12',
    imageUrl: '/spiceroute/13.jpg',
    description: 'Spice Route - Interior details 9',
    imageHint: 'restaurant-detail-9',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-spice-route-13',
    imageUrl: '/spiceroute/14.jpg',
    description: 'Spice Route - Interior details 10',
    imageHint: 'restaurant-detail-10',
    width: 1200,
    height: 800,
  },

  // ===== THE GRAND HALL (Hospitality/Banquet) - 4 images =====
  {
    id: 'cover-grand-hall',
    imageUrl: '/thegrandhall/1.jpg',
    description: 'The Grand Hall - Main hall',
    imageHint: 'banquet-main-hall',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-grand-hall-1',
    imageUrl: '/thegrandhall/2.jpg',
    description: 'The Grand Hall - Stage area',
    imageHint: 'banquet-stage',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-grand-hall-2',
    imageUrl: '/thegrandhall/3.jpg',
    description: 'The Grand Hall - Seating arrangement',
    imageHint: 'banquet-seating',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-grand-hall-3',
    imageUrl: '/thegrandhall/4.jpg',
    description: 'The Grand Hall - Chandelier details',
    imageHint: 'banquet-chandelier',
    width: 1200,
    height: 800,
  },

  // ===== SERENE DENTAL CLINIC (Healthcare/Clinic) - 7 images =====
  {
    id: 'cover-serene-clinic',
    imageUrl: '/sereneclinic/1.jpg',
    description: 'Serene Dental Clinic - Reception',
    imageHint: 'clinic-reception',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-serene-clinic-1',
    imageUrl: '/sereneclinic/2.jpg',
    description: 'Serene Dental Clinic - Waiting area',
    imageHint: 'clinic-waiting',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-serene-clinic-2',
    imageUrl: '/sereneclinic/3.jpg',
    description: 'Serene Dental Clinic - Treatment room',
    imageHint: 'clinic-treatment',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-serene-clinic-3',
    imageUrl: '/sereneclinic/4.jpg',
    description: 'Serene Dental Clinic - Consultation room',
    imageHint: 'clinic-consultation',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-serene-clinic-4',
    imageUrl: '/sereneclinic/5.jpg',
    description: 'Serene Dental Clinic - Equipment area',
    imageHint: 'clinic-equipment',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-serene-clinic-5',
    imageUrl: '/sereneclinic/6.jpg',
    description: 'Serene Dental Clinic - Corridor',
    imageHint: 'clinic-corridor',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-serene-clinic-6',
    imageUrl: '/sereneclinic/7.jpg',
    description: 'Serene Dental Clinic - Overall view',
    imageHint: 'clinic-overview',
    width: 1200,
    height: 800,
  },

  // ===== ARTWORK (Art Work) - 4 images =====
  {
    id: 'cover-artwork',
    imageUrl: '/artwork/1.jpg',
    description: 'Artwork - Featured piece',
    imageHint: 'artwork-featured',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-artwork-1',
    imageUrl: '/artwork/2.jpg',
    description: 'Artwork - Sculpture',
    imageHint: 'artwork-sculpture',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-artwork-2',
    imageUrl: '/artwork/3.jpg',
    description: 'Artwork - Wall art',
    imageHint: 'artwork-wall',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-artwork-3',
    imageUrl: '/artwork/4.jpg',
    description: 'Artwork - Installation',
    imageHint: 'artwork-installation',
    width: 1200,
    height: 800,
  },

  // ===== ABOUT PAGE =====
  {
    id: 'about-firm',
    imageUrl: '/about.jpg',
    description: 'Hardik Mistry - Interior Designer',
    imageHint: 'portrait-professional',
    width: 600,
    height: 800,
  },
];