import type { ImagePlaceholder } from './definitions';

export const PlaceHolderImages: ImagePlaceholder[] = [
  // ===== HERO IMAGE =====
  {
    id: 'hero-home',
    imageUrl: '/banner.jpg',
    description: 'Modern luxury interior design showcase',
    imageHint: 'hero-banner',
    width: 1920,
    height: 1080,
  },

  // ===== CATEGORY IMAGES =====
  {
    id: 'cat-residential',
    imageUrl: '/banner.jpg',
    description: 'Residential interior design',
    imageHint: 'category-residential',
    width: 800,
    height: 600,
  },
  {
    id: 'cat-corporate',
    imageUrl: '/banner.jpg',
    description: 'Commercial office space design',
    imageHint: 'category-commercial',
    width: 800,
    height: 600,
  },
  {
    id: 'cat-hospitality',
    imageUrl: '/banner.jpg',
    description: 'Hospitality interior design',
    imageHint: 'category-hospitality',
    width: 800,
    height: 600,
  },
  {
    id: 'cat-healthcare',
    imageUrl: '/banner.jpg',
    description: 'Healthcare facility design',
    imageHint: 'category-healthcare',
    width: 800,
    height: 600,
  },
  {
    id: 'cat-artwork',
    imageUrl: '/banner.jpg',
    description: 'Artistic interior elements',
    imageHint: 'category-artwork',
    width: 800,
    height: 600,
  },

  // ===== LIMPAIR OFFICE (Commercial/Office) =====
  {
    id: 'cover-limpair-office',
    imageUrl: '/Limpairoffice/1.jpg', // Main cover image
    description: 'Limpair Office - Modern office exterior',
    imageHint: 'commercial-office-building',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-limpair-1',
    imageUrl: '/Limpairoffice/2.jpg',
    description: 'Limpair Office - Reception area',
    imageHint: 'office-interior-reception',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-limpair-2',
    imageUrl: '/Limpairoffice/3.jpg',
    description: 'Limpair Office - Workspace',
    imageHint: 'office-interior-workspace',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-limpair-3',
    imageUrl: '/Limpairoffice/4.jpg',
    description: 'Limpair Office - Meeting room',
    imageHint: 'office-interior-meeting',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-limpair-4',
    imageUrl: '/Limpairoffice/5.jpg',
    description: 'Limpair Office - Lounge area',
    imageHint: 'office-interior-lounge',
    width: 1200,
    height: 800,
  },

  // ===== DAMAN RESIDENCE (Residential/Bungalows) =====
  {
    id: 'cover-daman-residence',
    imageUrl: '/damanresidence/1.jpg',
    description: 'Daman Residence - Exterior view',
    imageHint: 'residential-bungalow-exterior',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-1',
    imageUrl: '/damanresidence/2.jpg',
    description: 'Daman Residence - Living room',
    imageHint: 'residential-living-room',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-2',
    imageUrl: '/damanresidence/3.jpg',
    description: 'Daman Residence - Dining area',
    imageHint: 'residential-dining',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-3',
    imageUrl: '/damanresidence/4.jpg',
    description: 'Daman Residence - Master bedroom',
    imageHint: 'residential-bedroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-daman-4',
    imageUrl: '/damanresidence/5.jpg',
    description: 'Daman Residence - Kitchen',
    imageHint: 'residential-kitchen',
    width: 1200,
    height: 800,
  },

  // ===== RESIDENCE (Residential/Flats) =====
  {
    id: 'cover-residence',
    imageUrl: '/residence/1.jpg',
    description: 'Modern Residence - Apartment exterior',
    imageHint: 'residential-flat-exterior',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-1',
    imageUrl: '/residence/2.jpg',
    description: 'Modern Residence - Living space',
    imageHint: 'flat-interior-living',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-2',
    imageUrl: '/residence/3.jpg',
    description: 'Modern Residence - Kitchen',
    imageHint: 'flat-interior-kitchen',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-3',
    imageUrl: '/residence/4.jpg',
    description: 'Modern Residence - Bedroom',
    imageHint: 'flat-interior-bedroom',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-residence-4',
    imageUrl: '/residence/5.jpg',
    description: 'Modern Residence - Balcony',
    imageHint: 'flat-interior-balcony',
    width: 1200,
    height: 800,
  },

  // ===== VALSAD RESIDENCE (Residential/Bungalows) =====
  {
    id: 'cover-valsad-residence',
    imageUrl: '/valsadresidence/1.jpg',
    description: 'Valsad Residence - Front elevation',
    imageHint: 'residential-villa-exterior',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-1',
    imageUrl: '/valsadresidence/2.jpg',
    description: 'Valsad Residence - Entrance lobby',
    imageHint: 'residential-entrance',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-2',
    imageUrl: '/valsadresidence/3.jpg',
    description: 'Valsad Residence - Living area',
    imageHint: 'residential-living',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-3',
    imageUrl: '/valsadresidence/4.jpg',
    description: 'Valsad Residence - Dining room',
    imageHint: 'residential-dining',
    width: 1200,
    height: 800,
  },
  {
    id: 'gallery-valsad-4',
    imageUrl: '/valsadresidence/5.jpg',
    description: 'Valsad Residence - Garden view',
    imageHint: 'residential-garden',
    width: 1200,
    height: 800,
  },

  // ===== PLACEHOLDER IMAGES =====
  {
    id: 'placeholder-1',
    imageUrl: '/banner.jpg',
    description: 'Modern apartment interior',
    imageHint: 'interior-apartment',
    width: 800,
    height: 600,
  },
  {
    id: 'placeholder-2',
    imageUrl: '/banner.jpg',
    description: 'Gourmet kitchen design',
    imageHint: 'interior-kitchen-luxury',
    width: 800,
    height: 600,
  },
  {
    id: 'placeholder-3',
    imageUrl: '/banner.jpg',
    description: 'Spa bathroom interior',
    imageHint: 'interior-bathroom-spa',
    width: 800,
    height: 600,
  },
  {
    id: 'placeholder-4',
    imageUrl: '/banner.jpg',
    description: 'Restaurant interior',
    imageHint: 'interior-restaurant',
    width: 800,
    height: 600,
  },
  {
    id: 'placeholder-5',
    imageUrl: '/banner.jpg',
    description: 'Banquet hall design',
    imageHint: 'interior-banquet',
    width: 800,
    height: 600,
  },
  {
    id: 'placeholder-6',
    imageUrl: '/banner.jpg',
    description: 'Dental clinic interior',
    imageHint: 'interior-clinic',
    width: 800,
    height: 600,
  },
  {
    id: 'placeholder-7',
    imageUrl: '/banner.jpg',
    description: 'Bronze sculpture artwork',
    imageHint: 'artwork-sculpture',
    width: 800,
    height: 600,
  },

  // ===== ABOUT PAGE =====
  {
    id: 'about-firm',
    imageUrl: '/about.jpg',
    description: 'Hardik Mistry - Interior Designer',
    imageHint: 'portrait-professional',
    width: 600,
    height: 800,
  },
];